server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/Benfill/nexusbank-microservices'
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
        search-paths: configs
