server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: 'file:///C:/Users/youcode/Desktop/Projects/Breif/nexusbank-microservices'
          default-label: main
        search-paths: configs
