server:
  port: 8081
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://postgres:5432/customer-service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true