server:
  port: 8761

spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false    # Don't register itself
    fetchRegistry: false         # Don't fetch registry
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/